apiVersion: v1
kind: Service
metadata:
  name: app-service-lb
spec:
  selector:
    app: app
  ports:
  - port: 10800
    targetPort: 5000
  type: LoadBalancer
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
  replicas: 3
  serviceName: "app-service-lb"
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app-printbox
        image: printbox/recr-webapp-test:latest
        ports:
          - containerPort: 5000
            name: http-flask-pod
        livenessProbe:
          httpGet:
            path: /healtz
            port: 80
          periodSeconds: 10
        volumeMounts:
        - mountPath: /app/data/
          name: printbox-volume-1
      volumes:
      - name: printbox-volume-1
        hostPath:
          path: /home/user-1/volume-1
          type: DirectoryOrCreate
      topologySpreadConstraints:
        - topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: ScheduleAnyway
          maxSkew: 1
